import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create freeman",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="google-site-verification"
          content="K3lUxS_G851Bv2A3p2RImTdR_ZuD6vKCaZXQi4rIm0U"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
